import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-first-page',
  templateUrl: './first-page.component.html',
  styleUrls: ['./first-page.component.css']
})
export class FirstPageComponent implements OnInit {
  parentUrl="../../../assets/first-page/"
   icons:any[]=[
     {
       svgUrl:"../../../assets/first-page/1-1.svg",
       isSelected:false,
       description:''
     },
     {
      svgUrl:"../../../assets/first-page/1-2.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-3.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-4.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-5.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-6.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-7.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-8.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-9.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-10.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-11.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-12.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-13.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-14.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-15.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-16.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-17.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-18.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-19.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-20.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-21.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-22.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-23.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-24.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-25.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-26.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-27.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-28.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-29.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-30.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-31.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-32.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-33.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-34.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-35.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-36.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-37.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-38.svg",
      isSelected:false,
      description:''
    },
    {
      svgUrl:"../../../assets/first-page/1-39.svg",
      isSelected:false,
      description:''
    }];
    
   selectedicons:any[]=[];
  constructor() { }
  select(item: any){
    
    if(this.selectedicons.indexOf(item)!=-1){
      this.selectedicons.splice(this.selectedicons.indexOf(item),1);
      item.isSelected=false;
    }else{
      this.selectedicons.push(item);
      item.isSelected=true;
    }
    console.log(this.selectedicons);
  
  }
  ngOnInit(): void {
    // let url = 
   
  }

}
